

import type { Metadata } from 'next';
import './globals.css';

import { AppProvider } from '../context/AppContext';
import { UIProvider } from '../components/ui/UIProvider';

export const metadata: Metadata = {
  title: 'FitCore App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <AppProvider>
          <UIProvider>
            {children}
          </UIProvider>
        </AppProvider>
      </body>
    </html>
  );
}
